---
- name: Config and install nginx and HAProxy
  hosts: all
  become: true
  gather_facts: true

  vars:
    domain: "{{ hostvars[inventory_hostname].domain }}"
    ip: "{{ hostvars[inventory_hostname].ip }}"

  tasks:

    - name: Install haproxy and nginx
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - haproxy
        - nginx

    - name: Configure DNS records for HAProxy server
      template:
        src: dns_record.j2
        dest: "/etc/bind/{{ domain }}.zone"
      when: "{{ domain }} in {{ domain }}"
      loop: "{{ domain }}"
      notify: Reload DNS
    
    - name: Configure HAProxy
      template: 
        src: baseConfProxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      loop: "{{ domain }}"
      notify: Restart HAProxy

    - name: Creating HAProxy configuration files for domains
      template:
        src: baseConfProxy.j2
        dest: "/etc/haproxy/sites-available/{{ domain }}"
      loop: "{{ domain }}"
      become: true

    - name: copy Nginx and HAProxy config in enabled 
      command: >
        ln -s /etc/nginx/sites-available/{{ domain }} /etc/nginx/sites-enabled/{{ domain }} &&
        ln -s /etc/haproxy/sites-available/{{ domain }} /etc/haproxy/sites-enabled/{{ domain }}
      loop: "{{ domain }}"
      become: true

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Reload DNS
      service:
        name: bind9
        state: reloaded
...
