---
- hosts: all
  tasks:
    - name: Install haproxy and nginx
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - haproxy
        - nginx

    - name: Configure DNS records for web servers
      template:
        src: dns_record.j2
        dest: "/etc/bind/{{ item.domain }}.zone"
      with_items: "{{ domains }}"
      notify: Reload DNS
    
    - name: Configure HAProxy
      template:
        src: baseConfProxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart Nginx


  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Reload DNS
      service:
        name: bind9
        state: reloaded
...