---
- name: Config and install nginx and HAProxy
  hosts: localhost
  become: true
  tasks:
    - name: Install haproxy and nginx
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - haproxy
        - nginx

    - name: Configure DNS records for web servers
      template:
        src: dns_record.j2
        dest: "/etc/bind/{{ item.domain }}.zone"
      with_items: "{{ domains }}"
      notify: Reload DNS

    - name: Configure DNS records for HAProxy server
      template:
        src: dns_record.j2
        dest: "/etc/bind/{{ item.domain }}.zone"
      with_items: "{{ domains }}"
      when: "'example1.com' in item.domain"
      notify: Reload DNS
    
    - name: Configure HAProxy
      template: 
        src: baseConfProxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

    - name: Creating HAProxy configuration files for domains
      template:
        src: baseConfProxy.j2
        dest: "/etc/haproxy/sites-available/{{ item.domain }}"
      with_items: "{{ domains }}"
      become: true

    - name: copy Nginx and HAProxy config in enabled 
      command: >
        ln -s /etc/nginx/sites-available/{{ item.domain }} /etc/nginx/sites-enabled/{{ item.domain }} &&
        ln -s /etc/haproxy/sites-available/{{ item.domain }} /etc/haproxy/sites-enabled/{{ item.domain }}
      with_items: "{{ domains }}"
      become: true

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Reload DNS
      service:
        name: bind9
        state: reloaded
...
